# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readBCFQuery_ <- function(fname, reg, samplenames) {
    .Call('_windowlickr_readBCFQuery_', PACKAGE = 'windowlickr', fname, reg, samplenames)
}

readBCFContigs_ <- function(fname) {
    .Call('_windowlickr_readBCFContigs_', PACKAGE = 'windowlickr', fname)
}

readBCFSamples_ <- function(fname) {
    .Call('_windowlickr_readBCFSamples_', PACKAGE = 'windowlickr', fname)
}

